spring:
  application:
    name: What4Dinner_dash_service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://136.114.213.6:5432/w4d}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:W4dyun2026!}
  sql:
    init:
      mode: always

server:
  port: 8082
  servlet:
    context-path: /api

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expiration-minutes: 60
